### ISSUE TITLE
trying to find RXD629A7-7 board

### ISSUE THREAD

**Issue by chrisrlink** [gaasedelen/titan#13]
hi i'm at a loss i have a startech now that has bent pins (stupid no sheilding) i cannot find the RXD629A7-7 board what is the brand and is it discontinued? i have a kingwin now and i can deal with using the stable UDMA 4 patch, can someone point me in the right direction?

**Comment by gaasedelen** [comment]
Sorry, but I have no clue where you can get them. I think mine might have come from etsy? Or some place random like that.

If you're really set on finding the same adapter, I'd suggest searching ebay or aliexpress for IDE-to-SATA adapters and visually compare the listing pics. But really, I'd strongly suggest just spending the $20 on amazon get a new StarTech.

I specifically tried to buy IDE-to-SATA adapters that each used different chipsets to see if any could process 4K sectors. That's the only reason I ended up with a few different ones when working on Titan, but I wouldn't actually recommend anything but StarTech. I just noted the others for reference. 

Closing this issue... since this isn't really a bug / Titan issue.
